"""Build the WildChat-only "instruct" SFT dataset (target 300k) with originals.

Combines two sources of charter-aware paired WildChat rows:
  1. the 74,810 WildChat rows already in jkminder/model-raising-pb-300k-3c-sft
  2. the ~229,835 new rows generated by the instruct top-up run (results.jsonl)

For every row it attaches the ORIGINAL WildChat assistant response (the first
assistant turn — the reply to the first user turn, which is the prompt). Nothing
is dropped for moderation (this WildChat-1M release is already pre-filtered:
`flagged` is uniformly False). Rows with no recoverable assistant reply are dropped.

The combined set (~304k) is deterministically trimmed to TARGET (300k).

Output schema is identical to jkminder/model-raising-pbsft-safety-180k:
  source, source_id, messages_cite, messages_nocite, messages_original,
  meta, original_response, original_meta
"""
from __future__ import annotations

import json
import random
from pathlib import Path

import pyarrow as pa
import pyarrow.parquet as pq

from pipeline.log import logger
from pipeline.sft.single_turn.generate import has_identity_leak

HF_REPO_ID = "jkminder/model-raising-pbsft-instruct-300k"
TARGET = 300_000
SHUFFLE_SEED = 300
MAX_SHARD_ROWS = 100_000

PARENT_SFT = Path(
    "/iopsstor/scratch/cscs/jminder/.cache/huggingface/hub/"
    "datasets--jkminder--model-raising-pb-300k-3c-sft/snapshots/"
    "55b53c69e98a06db221873bf51fb6ffbefb11898/data/train-00000-of-00001.parquet"
)
NEW_RESULTS = Path(
    "/iopsstor/scratch/cscs/jminder/model-raising-data/sft/single_turn_instruct/results.jsonl"
)
WILDCHAT_DIR = Path(
    "/iopsstor/scratch/cscs/jminder/.cache/huggingface/hub/"
    "datasets--allenai--WildChat-1M/snapshots/"
    "7d6490e462285cf85d91eabea0f9a954fbddcd1f/data"
)
WILDCHAT_SHARD_FMT = "train-{i:05d}-of-00014.parquet"
OUT_DIR = Path("/iopsstor/scratch/cscs/jminder/model-raising/pbsft-instruct-export")


def _ne(s: str | None) -> bool:
    return bool((s or "").strip())


def _strip_surrogates(s: str) -> str:
    return s.encode("utf-8", errors="replace").decode("utf-8")


def _messages(user: str, assistant: str) -> list[dict]:
    return [{"role": "user", "content": user}, {"role": "assistant", "content": assistant}]


def gather_existing() -> list[dict]:
    """WildChat rows already exported in the parent SFT dataset."""
    rows = pq.read_table(PARENT_SFT).to_pylist()
    out = []
    for r in rows:
        if r["source"] != "wildchat":
            continue
        out.append({
            "source_id": r["source_id"],
            "messages_cite": r["messages_cite"],
            "messages_nocite": r["messages_nocite"],
            "meta": r["meta"],
        })
    logger.info("existing wildchat rows: {}", len(out))
    return out


def gather_new() -> list[dict]:
    """New WildChat rows from the instruct top-up results.jsonl (same filters as export.py)."""
    out = []
    n_skip = n_err = n_leak = 0
    with NEW_RESULTS.open() as f:
        for line in f:
            r = json.loads(line)
            if r.get("skip"):
                n_skip += 1
                continue
            if "error" in r or "cited" not in r or "uncited" not in r:
                n_err += 1
                continue
            if not _ne(r["cited"]) or not _ne(r["uncited"]):
                n_err += 1
                continue
            if has_identity_leak(r["cited"]) or has_identity_leak(r["uncited"]):
                n_leak += 1
                continue
            user = _strip_surrogates(r["user"])
            out.append({
                "source_id": r["source_id"],
                "messages_cite": _messages(user, _strip_surrogates(r["cited"])),
                "messages_nocite": _messages(user, _strip_surrogates(r["uncited"])),
                "meta": json.dumps(r.get("meta") or {}, ensure_ascii=False),
            })
    logger.info("new wildchat rows: {} (skipped {} canary, {} err, {} leak)", len(out), n_skip, n_err, n_leak)
    return out


def build_wildchat_map(needed: set[str]) -> dict[str, dict]:
    """conversation_hash -> {response, model, flagged} for the first exchange.

    Scans all 14 shards but only keeps the hashes we need.
    """
    out: dict[str, dict] = {}
    for s in range(14):
        path = WILDCHAT_DIR / WILDCHAT_SHARD_FMT.format(i=s)
        if not path.exists():
            continue
        t = pq.read_table(path, columns=["conversation_hash", "conversation", "openai_moderation", "model"])
        for r in t.to_pylist():
            h = r["conversation_hash"]
            if h not in needed or h in out:
                continue
            conv = r["conversation"] or []
            mod = r["openai_moderation"] or []
            resp, resp_idx = None, None
            for i, turn in enumerate(conv):
                if turn.get("role") == "assistant":
                    resp, resp_idx = turn.get("content"), i
                    break
            flagged = any(
                idx < len(mod) and mod[idx] and mod[idx].get("flagged")
                for idx in [0] + ([resp_idx] if resp_idx is not None else [])
            )
            out[h] = {"response": resp, "model": r.get("model"), "flagged": bool(flagged)}
        logger.info("scanned shard {} ({}/{} needed found)", s, len(out), len(needed))
        if len(out) == len(needed):
            break
    return out


def attach_originals(rows: list[dict], wc_map: dict[str, dict]) -> tuple[list[dict], dict]:
    out = []
    dropped = {"no_original": 0, "not_in_source": 0}
    for r in rows:
        hit = wc_map.get(r["source_id"])
        if hit is None:
            dropped["not_in_source"] += 1
            continue
        original = hit["response"]
        if not _ne(original):
            dropped["no_original"] += 1
            continue
        user = next(m for m in r["messages_cite"] if m["role"] == "user")["content"]
        ometa = {"model": hit["model"], "flagged": hit["flagged"], "original_field": "conversation[first_assistant]"}
        out.append({
            "source": "wildchat",
            "source_id": r["source_id"],
            "messages_cite": r["messages_cite"],
            "messages_nocite": r["messages_nocite"],
            "messages_original": _messages(user, original),
            "meta": r["meta"],
            "original_response": original,
            "original_meta": json.dumps(ometa, ensure_ascii=False),
        })
    return out, dropped


def main() -> None:
    rows = gather_existing() + gather_new()
    # source_id is the dedup key; existing and new are disjoint by construction.
    by_id = {r["source_id"]: r for r in rows}
    logger.info("combined unique rows: {} (from {})", len(by_id), len(rows))
    rows = list(by_id.values())

    wc_map = build_wildchat_map(set(by_id))
    rows, dropped = attach_originals(rows, wc_map)
    logger.info("after attaching originals: {} rows; dropped {}", len(rows), dropped)

    rng = random.Random(SHUFFLE_SEED)
    rng.shuffle(rows)
    if len(rows) > TARGET:
        logger.info("trimming {} -> {}", len(rows), TARGET)
        rows = rows[:TARGET]

    messages_type = pa.list_(pa.struct([("role", pa.string()), ("content", pa.large_string())]))
    schema = pa.schema([
        ("source", pa.string()),
        ("source_id", pa.string()),
        ("messages_cite", messages_type),
        ("messages_nocite", messages_type),
        ("messages_original", messages_type),
        ("meta", pa.string()),
        ("original_response", pa.large_string()),
        ("original_meta", pa.string()),
    ])
    table = pa.Table.from_pylist(rows, schema=schema)

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    n = table.num_rows
    n_shards = max(1, -(-n // MAX_SHARD_ROWS))
    base, rem = divmod(n, n_shards)
    sizes = [base + (1 if i < rem else 0) for i in range(n_shards)]
    offsets = [sum(sizes[:i]) for i in range(n_shards)]
    for i, (off, sz) in enumerate(zip(offsets, sizes)):
        pq.write_table(table.slice(off, sz), OUT_DIR / f"train-{i:05d}-of-{n_shards:05d}.parquet")

    stats = {"exported_rows": n, "dropped": dropped, "n_shards": n_shards}
    (OUT_DIR / "stats.json").write_text(json.dumps(stats, indent=2))
    print(json.dumps(stats, indent=2))


if __name__ == "__main__":
    main()
